export interface ServerSettings {
  id: string;
  scannerFindCovers: boolean;
  scannerCoverProvider: string;
  scannerParseSubtitle: boolean;
  scannerPreferMatchedMetadata: boolean;
  scannerDisableWatcher: boolean;
  storeCoverWithItem: boolean;
  storeMetadataWithItem: boolean;
  metadataFileFormat: string;
  rateLimitLoginRequests: number;
  rateLimitLoginWindow: number;
  allowIframe: boolean;
  backupPath: string;
  backupSchedule: boolean;
  backupsToKeep: number;
  maxBackupSize: number;
  loggerDailyLogsToKeep: number;
  loggerScannerLogsToKeep: number;
  homeBookshelfView: number;
  bookshelfView: number;
  podcastEpisodeSchedule: string;
  sortingIgnorePrefix: boolean;
  sortingPrefixes: string[];
  chromecastEnabled: boolean;
  dateFormat: string;
  timeFormat: string;
  language: string;
  allowedOrigins: string[];
  logLevel: number;
  version: string;
  buildNumber: number;
  authLoginCustomMessage: string | null;
  authActiveAuthMethods: string[];
  authOpenIDIssuerURL: string;
  authOpenIDAuthorizationURL: string;
  authOpenIDTokenURL: string;
  authOpenIDUserInfoURL: string;
  authOpenIDJwksURL: string;
  authOpenIDLogoutURL: string;
  authOpenIDTokenSigningAlgorithm: string;
  authOpenIDButtonText: string;
  authOpenIDAutoLaunch: boolean;
  authOpenIDAutoRegister: boolean;
  authOpenIDMatchExistingBy: string | null;
  authOpenIDSubfolderForRedirectURLs: string;
}